# $FreeBSD: releng/10.1/usr.bin/make/tests/suffixes/src_wild2/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/suffixes/src_wild2

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		Makefile.test
FILES+=		TEST1.a
FILES+=		TEST2.a
FILES+=		expected.status.1
FILES+=		expected.stderr.1
FILES+=		expected.stdout.1

.include <bsd.test.mk>
