# $FreeBSD: releng/10.1/usr.bin/make/tests/basic/t3/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/basic/t3

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		expected.status.1
FILES+=		expected.stderr.1
FILES+=		expected.stdout.1

.include <bsd.test.mk>
