# $FreeBSD: releng/10.1/tests/sys/Makefile 265586 2014-05-07 18:49:25Z asomers $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/..

TESTS_SUBDIRS+=		kern
TESTS_SUBDIRS+=		netinet
TESTSDIR= ${TESTSBASE}/sys

KYUAFILE= yes

.include <bsd.test.mk>
