# $FreeBSD: releng/10.1/usr.bin/make/tests/archives/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/archives

TESTS_SUBDIRS=	fmt_44bsd fmt_44bsd_mod fmt_oldbsd

.include <bsd.test.mk>
