# $FreeBSD: releng/10.1/usr.sbin/bsdconfig/examples/Makefile 272230 2014-09-27 23:57:21Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		add_some_packages.sh browse_packages_http.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
