# $FreeBSD: releng/10.1/usr.bin/make/tests/suffixes/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/suffixes

TESTS_SUBDIRS=	basic src_wild1 src_wild2

.include <bsd.test.mk>
