# $FreeBSD: releng/10.1/usr.bin/make/tests/syntax/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/syntax

TESTS_SUBDIRS=	directive-t0 enl funny-targets semi

.include <bsd.test.mk>
