# $FreeBSD: releng/10.1/usr.bin/make/tests/execution/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/execution

TESTS_SUBDIRS=	ellipsis empty joberr plus

.include <bsd.test.mk>
