# $FreeBSD: releng/10.1/tools/tools/cxgbetool/Makefile 259142 2013-12-09 22:40:22Z np $

PROG=	cxgbetool
SRCS=	cxgbetool.c
NO_MAN=
CFLAGS+= -I${.CURDIR}/../../../sys/dev/cxgbe -I${.CURDIR}/../../../sys -I.
BINDIR?= /usr/sbin

.include <bsd.prog.mk>
