# $FreeBSD: releng/10.1/usr.bin/make/tests/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make

FILESDIR=	${TESTSDIR}
FILES=		common.sh
FILES+=		test-new.mk

TESTS_SUBDIRS=	archives
TESTS_SUBDIRS+=	basic
TESTS_SUBDIRS+=	execution
TESTS_SUBDIRS+=	shell
TESTS_SUBDIRS+=	suffixes
TESTS_SUBDIRS+=	syntax
TESTS_SUBDIRS+=	sysmk
TESTS_SUBDIRS+=	variables

.include <bsd.test.mk>
