# $FreeBSD: releng/10.1/share/man/man4/man4.arm/Makefile 266338 2014-05-17 19:06:46Z loos $

MAN=	devcfg.4 \
	mge.4 \
	npe.4 \
	ti_adc.4

MLINKS= mge.4 if_mge.4
MLINKS+=npe.4 if_npe.4

MANSUBDIR=/arm

.include <bsd.prog.mk>
