# $FreeBSD: releng/10.1/usr.bin/make/tests/variables/modifier_t/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/variables/modifier_t

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		Makefile.test
FILES+=		expected.status.1
FILES+=		expected.status.2
FILES+=		expected.status.3
FILES+=		expected.stderr.1
FILES+=		expected.stderr.2
FILES+=		expected.stderr.3
FILES+=		expected.stdout.1
FILES+=		expected.stdout.2
FILES+=		expected.stdout.3

.include <bsd.test.mk>
