# $FreeBSD: releng/10.1/usr.bin/make/tests/variables/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/variables

TESTS_SUBDIRS=	modifier_M modifier_t opt_V t0

.include <bsd.test.mk>
