# $FreeBSD: releng/10.1/usr.bin/make/tests/sysmk/t1/mk/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/sysmk/t1/mk

FILESDIR=		${TESTSDIR}
FILES=			sys.mk.test
FILESNAME_sys.mk.test=	sys.mk

.include <bsd.test.mk>
