# $FreeBSD: releng/10.1/usr.bin/make/tests/shell/path_select/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/shell/path_select

TAP_TESTS_SH=	legacy_test

FILESDIR=	${TESTSDIR}
FILES=		Makefile.test
FILES+=		expected.status.1
FILES+=		expected.status.2
FILES+=		expected.stderr.1
FILES+=		expected.stderr.2
FILES+=		expected.stdout.1
FILES+=		expected.stdout.2
FILES+=		shell

.include <bsd.test.mk>
