# $FreeBSD: releng/10.1/usr.bin/make/tests/shell/Makefile 264996 2014-04-27 01:15:10Z jmmv $

TESTSDIR=	${TESTSBASE}/usr.bin/make/shell

TESTS_SUBDIRS=	builtin meta path path_select replace select

.include <bsd.test.mk>
